rmdir /S /Q .\nativePC\NPC\npc001\
rmdir /S /Q .\nativePC\NPC\npc002\
rmdir /S /Q .\nativePC\NPC\npc003\
rmdir /S /Q .\nativePC\NPC\npc004\
rmdir /S /Q .\nativePC\NPC\npc005\
rmdir /S /Q .\nativePC\NPC\npc006\
rmdir /S /Q .\nativePC\NPC\npc007\
rmdir /S /Q .\nativePC\NPC\npc009\
rmdir /S /Q .\nativePC\NPC\npc010\
rmdir /S /Q .\nativePC\NPC\npc011\
rmdir /S /Q .\nativePC\NPC\npc012\
rmdir /S /Q .\nativePC\NPC\npc014\
rmdir /S /Q .\nativePC\NPC\npc015\
rmdir /S /Q .\nativePC\NPC\npc016\
rmdir /S /Q .\nativePC\NPC\npc017\
rmdir /S /Q .\nativePC\NPC\npc018\
rmdir /S /Q .\nativePC\NPC\npc019\
rmdir /S /Q .\nativePC\NPC\npc020\
rmdir /S /Q .\nativePC\NPC\npc021\
rmdir /S /Q .\nativePC\NPC\npc022\
rmdir /S /Q .\nativePC\NPC\npc023\
rmdir /S /Q .\nativePC\NPC\npc024\
rmdir /S /Q .\nativePC\NPC\npc025\
rmdir /S /Q .\nativePC\NPC\npc026\
rmdir /S /Q .\nativePC\NPC\npc027\
rmdir /S /Q .\nativePC\NPC\npc028\
rmdir /S /Q .\nativePC\NPC\npc029\
rmdir /S /Q .\nativePC\NPC\npc030\
rmdir /S /Q .\nativePC\NPC\npc032\
rmdir /S /Q .\nativePC\NPC\npc033\
rmdir /S /Q .\nativePC\NPC\npc034\
rmdir /S /Q .\nativePC\NPC\npc035\
rmdir /S /Q .\nativePC\NPC\npc036\
rmdir /S /Q .\nativePC\NPC\npc037\
rmdir /S /Q .\nativePC\NPC\npc038\
rmdir /S /Q .\nativePC\NPC\npc039\
rmdir /S /Q .\nativePC\NPC\npc040\
rmdir /S /Q .\nativePC\NPC\npc102\
rmdir /S /Q .\nativePC\NPC\npc103\
rmdir /S /Q .\nativePC\NPC\npc104\
rmdir /S /Q .\nativePC\NPC\npc105\
rmdir /S /Q .\nativePC\NPC\npc106\
rmdir /S /Q .\nativePC\NPC\npc107\
rmdir /S /Q .\nativePC\NPC\npc108\
rmdir /S /Q .\nativePC\NPC\npc109\
rmdir /S /Q .\nativePC\NPC\npc111\
rmdir /S /Q .\nativePC\NPC\npc112\
rmdir /S /Q .\nativePC\NPC\npc113\
rmdir /S /Q .\nativePC\NPC\npc114\
rmdir /S /Q .\nativePC\NPC\npc116\
rmdir /S /Q .\nativePC\NPC\npc117\
rmdir /S /Q .\nativePC\NPC\npc118\
rmdir /S /Q .\nativePC\NPC\npc121\
rmdir /S /Q .\nativePC\NPC\npc123\
rmdir /S /Q .\nativePC\NPC\npc124\
rmdir /S /Q .\nativePC\NPC\npc125\
rmdir /S /Q .\nativePC\NPC\npc130\
rmdir /S /Q .\nativePC\NPC\npc131\
rmdir /S /Q .\nativePC\NPC\npc134\
rmdir /S /Q .\nativePC\NPC\npc140\
rmdir /S /Q .\nativePC\NPC\npc251\
rmdir /S /Q .\nativePC\NPC\npc252\
rmdir /S /Q .\nativePC\NPC\npc253\
rmdir /S /Q .\nativePC\NPC\npc254\
rmdir /S /Q .\nativePC\NPC\npc255\
rmdir /S /Q .\nativePC\NPC\npc256\
rmdir /S /Q .\nativePC\NPC\npc257\
rmdir /S /Q .\nativePC\NPC\npc258\
rmdir /S /Q .\nativePC\NPC\npc301\
rmdir /S /Q .\nativePC\NPC\npc302\
rmdir /S /Q .\nativePC\NPC\npc303\
rmdir /S /Q .\nativePC\NPC\npc304\
rmdir /S /Q .\nativePC\NPC\npc305\
